### ISSUE TITLE
QDM based Patient data sample that would work with AIS Measure CQL

### ISSUE THREAD

**Issue by ramanathanga** [MeasureAuthoringTool/bonnie#1249]
Hi,

We are trying to execute a measure CQL that uses QDM data as input.

We already tested a sample based on Readme as below, this was successful:
[(https://github.com/projecttacoma/cqm-execution/blob/master/README.md)]

Below are the 6 CQL measures published by NCQA which we have access to, and while trying to execute AIS measure CQL we understand we need a QDM based Patient and other related data.

Measures: AIS, ASF, DMS, DRR, DSF, PRS

**We are trying to get a QDM based Patient data sample that would work with AIS Measure CQL, can you pls. share a sample that we could use to test.

Larger picture, we are trying to understand how to create/generate QDM based data for Patient and other types as inputs to NCQA measures CQL (like AIS, ASF, DMS, DRR, DSF, PRS etc..). Are there any resources which you can point us to.**

Thanks,
Ganesh Ramanathan, Balaji Venkata Yadalla.

**Comment by mayerm94** [comment]
Ganesh,

Based on your description, it sounds like you are trying to test a measure that uses CQL-based logic. This can be done on either https://bonnie.healthit.gov or https://bonnie-prior.healthit.gov/ depending on what version of CQL and QDM the measure was written in.
If you are interested in programmatically creating QDM-based patients, you should checkout the cqm-models repository https://github.com/projecttacoma/cqm-models. Specifically, you should look at the patient generation script https://github.com/projecttacoma/cqm-models/blob/master/lib/generate_patients.rb which creates a patient object containing QDM data elements, these patients can be used to calculate against measures using the cqm-execution repository https://github.com/projecttacoma/cqm-execution/.

-Matt

**Comment by mayerm94** [comment]
Closing this ticket because it is a duplicate to https://github.com/projecttacoma/cqm-models/issues/122
