### ISSUE TITLE
CQM-Models update

### ISSUE THREAD

**Issue by dczulada** [MeasureAuthoringTool/bonnie#2096]
@adongare 

Just wanted to make sure you're aware of the cqm-models 4.1.0 version released on May 27th
https://github.com/projecttacoma/cqm-models/tree/v4.1.0

This update includes the cql-execution v2.4.1 update (https://github.com/cqframework/cql-execution/releases/tag/v2.4.1) which fixes the calculation bug identified with EKI-16.
https://oncprojectracking.healthit.gov/support/browse/EKI-16

I also believe cql-execution 2.4.1 also fixes the "Timezone Bug" that this PR was attempting to fix.
https://github.com/MeasureAuthoringTool/bonnie/pull/2029

**Comment by adongare** [comment]
Thank you @dczulada! I'll let our PO know about it. cc: @jkotanchik-SB

**Comment by dczulada** [comment]
Ashok (@adongare) @jkotanchik-SB .  Just wanted to check back in to see if this update to cqm-models is on the radar to bring into Bonnie before this year's AU.  The bug in cql-execution (that this update fixes) can hide bugs in the measure logic.

**Comment by adongare** [comment]
@dczulada thanks for the reminder! We had discussed this with POs and looks like we don't have the bandwidth right now to integrate this as we are heads down with the MADiE MVP release. We will be evaluating this after the MADiE MVP release. We have created an internal ticket to track this.
